### ISSUE TITLE
Graph CLI Auth

### ISSUE THREAD

**Issue by Jannis** [graphprotocol/graph-cli#158]
Specification:

- [ ] Add `graph auth <node> <auth token>` command that updates a config file with auth token (https://github.com/graphprotocol/graph-cli/issues/159)
- [ ] Rename `--api-key` to `--auth-token` (https://github.com/graphprotocol/graph-cli/issues/159)
- [ ] Use the right auth token when running `graph deploy --node <node>` (https://github.com/graphprotocol/graph-cli/issues/159)

**Comment by leodasvacas** [comment]
We can use this lib https://www.npmjs.com/package/keytar to put it the token on the OS secret store.

**Comment by timmclean** [comment]
Should `--auth-token` be an environment variable instead?

**Comment by Jannis** [comment]
I think we should do both:`GRAPH_AUTH_TOKEN` + `--auth-token`.
